server:
  port: 8443
  http2:
    enabled: false
  ssl:
    enabled: false
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    protocol: TLSv1.2

debug: false

spring:
  resources:
    cache:
      period: 604800
  chain:
    compressed: true
    cache: true
  thymeleaf:
    prefix: classpath:/templates/
    #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234@Abcd
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    #redis密码，没有密码的可以用～表示
    password: ~
    pool:
      max-active: 100
      max-idle: 10
      max-wait: 100000
# Mybatis mapper 映射路径配置
mybatis:
   # mapper-locations: classpath:mapper/*.xml
   config-location: classpath:mybatis-config.xml

# 日志输出
logging:
  level:
    root: INFO